<a href="https://colab.research.google.com/github/bee20/Coding_Practice/blob/main/Python_Coding_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#find missing number -> O(n^2) complexity
l = [3,4,6,7,10]

l2 = []
for i in range(l[0],l[-1]+1):
  l2.append(i)
# print(l2)

l3 = []
for j in l2:
  if j not in l:
    l3.append(j)
print(l3)


[5, 8, 9]


In [ ]:
#find missing number -> O(n)complexity
lst = [3,4,6,7,10]
n = len(lst)
b=[0]*(lst[ n-1]+1)

for i in range(n):
  # print(b[lst[i] ])
  b[lst[i] ]=1

for i in range(lst[0],lst[n-1]+1):
  if b[i]==0:
    print(i,end=" ")

5 8 9 

In [ ]:
# largest string

str = "hi bb this side"
l=0
word=''
for i in str.split(' '):
  if len(i) >= l:
    l= len(i)
    word = i
word

In [ ]:
# factorial
ans=1
for i in range(2,n+2):
  # print(i-1)
  k =i-1
  ans = ans*k
  print(ans,k)
ans

1 1
2 2
6 3
24 4
120 5
720 6
5040 7
40320 8


40320

In [ ]:
# factorial
factorial=1
n= 9
for i in range(1,9):
  print(i)
  factorial = factorial*(i+1)
print(factorial)

1
2
3
4
5
6
7
8
362880


In [ ]:
# write code to sort list

l = [3,4,6,6,7,8,3]

for i in range(0,len(l)):
  print(i)
  for j in range(i+1,len(l)):
    if l[i]> l[j]:
      l[i], l[j] = l[j], l[i]
print(l)


0
1
2
3
4
5
6
[3, 3, 4, 6, 6, 7, 8]


In [ ]:
# find median

l = [3,4,6,6,7,8,3,6,2]
for i in range(0,len(l)):
  # print(i)
  for j in range(i+1,len(l)):
    if l[i]> l[j]:
      l[i], l[j] = l[j], l[i]

if len(l)%2 != 0:
  median = l[round(len(l)/2)]
else:
  median = (l[round(len(l)/2)] + l[round(len(l)/2)+1])/2

print(len(l),median)

9 6


In [ ]:
# # write code to find mode
# lst = [3,4,6,6,7,8,3,6]
# dict = {}


# for i in range(0,len(lst)):
#   cnt=1
#   for j in range(i+1, len(lst)):
#     if lst[i] == lst[j]:
#       cnt= cnt +1
#       print(lst[i], lst[j], cnt )
#   print(cnt)
#   dict[ lst[i] ] = cnt

# # print(dict)

# # for k,i in dict.items():
# #   if i == max(list( dict.values() )):
# #     print(k)



In [ ]:
# Create a dictionary which counts the number of characters in a word.

dct = {}

l = 'hi i am barkha'

for i in l.split():
  dct[i] = len(i)
print(dct)

{'hi': 2, 'i': 1, 'am': 2, 'barkha': 6}


In [ ]:
len(m2)

3

In [ ]:
# Multiply 2 Matrix.

m1 = [[1,2,3],
      [2,3,0]]
m2 = [[0,0],
      [1,0],
      [0,0]]
m3=[[0,0],
    [0,0]]

# print(m1,m2)

for i in range(len(m1)):
  for j in range(len(m2[0] )):
    for k in range(len(m2)):
      m3[i][j] += m1[i][k] * m2[k][j]
      # result[i][j] += X[i][k] * Y[k][j]
m3

[[2, 0], [3, 0]]

In [ ]:
# generate n grams

sent = 'machine learning nlp deep learn word2vec'
n= 5
lst = []

for i in range(0, len(sent.split())-n+1 ):
  lst.append(sent.split()[i:n])
  print(i,n)
  n=n+1
lst

0 5
1 6


[['machine', 'learning', 'nlp', 'deep', 'learn'],
 ['learning', 'nlp', 'deep', 'learn', 'word2vec']]

In [ ]:
# you are given a character string A having length N.
# You have to find the character having maximum number of occurrences in the string and return its ASCII code.
# If there are multiple such characters, then return the ASCII code having least value.

A = "aabbccc"

v= -1
d = {}

for i in range(len(A)):
  # print( ord(A[i]))
  if ord(A[i]) in d.keys() :
    v = v - 1
    d.update({ord(A[i]): v   })
  else:
    d.update({ord(A[i]):  v  })
    v= -1

print(d)

ls = []
minn = min(d.values())
for i in d:
  if d[i] == minn:
    ls.append(i)
print(min(ls))

{97: -2, 98: -2, 99: -3}
99


In [ ]:
# Given an array X, the value of gamma and beta. Perform Batch Normalization on array X.

# Use the formulas below to compute the X_updated array.

# n -> size of X
# mu -> mean of array X
# sig -> standard deviation of array X
# standard-deviance = sqrt ( sum[ (Xi - mu)2 ] / n-1 )
# X_standardised = (Xi - mu)/sig
# X_updated = gamma*X_standardised + beta
# Return the X_updated array.

n = 8
x = [1, 3, 2, 5, 7, 3, 2, 4]
g = 2
b = 1

import numpy as np
x_ar = np.array(x)
m = sum(x_ar)/n

s = np.sqrt((np.sum( np.square(x_ar- m) )/ (n-1)))

# ss = np.std(x_ar) this is different sd from above manual formula
x_s = (x_ar - m)/s
x_f = np.around( g*x_s + b, 2)
x_f


array([-1.47,  0.61, -0.43,  2.69,  4.77,  0.61, -0.43,  1.65])

In [ ]:
# You teach a class of students. You plan to make a pair where you want to pair 2 of your students who live closest to each other. The map along with the coordinates of each student's house is available to you. Can you find the students whom you can pair? You are given 2 lists containing the students name and locations. Manhattan Distance will be used to calculate the distance between 2 points.
# Manhattan Distance between 2 points (x1,y1) and (x2,y2) is given by |x1-x2| + |y1-y2|.

names = ['Adam','Millie','Jacob','Michael','Maxine']
loc = [(1,2),(5,4),(0,3),(2,3),(0,0)]

# Example Output: [‘Adam’,‘Jacob’]

d = {}
for i in range(len(names)):
  for j in range(i+1,len(names)):
    m =  abs(loc[i][0] - loc[j][0]) + abs(loc[i][1] - loc[j][1])
    if m in d:
      d[m].extend([[names[i], names[j]]])
    else:
      d[m] = [[names[i], names[j]]]
    # print(i,j,loc[i], loc[j], m, d)

minn = min(d.keys())
print(d )
print(minn,d[minn][0])

{6: [['Adam', 'Millie'], ['Millie', 'Jacob']], 2: [['Adam', 'Jacob'], ['Adam', 'Michael'], ['Jacob', 'Michael']], 3: [['Adam', 'Maxine'], ['Jacob', 'Maxine']], 4: [['Millie', 'Michael']], 9: [['Millie', 'Maxine']], 5: [['Michael', 'Maxine']]}
2 ['Adam', 'Jacob']


In [ ]:
arr = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77],
                    [11, 45, 77]])

# sum(np.diag(arr))
# arr[arr[:,0]>11, 1:]
len(arr)

4

In [ ]:
(np.diagonal(arr)).sum()

176

In [ ]:
a = [0,1,0,2,0,0,3,0,5,7,0,0,8]
na = np.array(a)
res = np.where(na == 0)[0]
res

array([ 0,  2,  4,  5,  7, 10, 11])

In [ ]:
txt = "890"

x = txt.isdigit()

print(x)

True


In [ ]:
txt = "Hello World"[::-1]
print(txt)

dlroW olleH


In [ ]:
sd = {'c' :{'s' : {'n':'mik', 'm':{'math':70, 'hist':80}}}}

sd['c']['s']['m']['hist']

80

In [ ]:
# ol = [10, 4, 5 , 3 , 11]
# l = len(ol)
# n = 2

# n = n %l
# ls = []
# for i in range(l):
#   ni = (i+n)%l
#   print(ni, ol[ni])
#   ls.append(ol[ni])
# ls

2 5
3 3
4 11
0 10
1 4


[5, 3, 11, 10, 4]

In [ ]:
# a= -1
# b=-3
# c=3
# d= 1
# n=150
# ls = []
# g ={}
# for i in range(0,n+1):
#   f = a* i^3 +b * i^2 + c*i^1 + d
#   g[i] = f
# minn = min(g.values())

# for i in g:
#   if g[i] == minn:
#     ls.append(-i)

# print(min(ls)*-1)

1


In [ ]:
import pandas as pd
import numpy as np
# df = pd.DataFrame({"nm_ak":['ab_15', 'bc_29']})
# df[['n', 'a']] = df['nm_ak'].str.split('_')

# df = pd.DataFrame({"b":[4, 12], "c":[6, 7]})
# df[df['b']%2 == 0]['c'][0]*2

x= np.array([-5, 9, -8,15,16])
x[ (x>= -5) & (x <=15)] *= -1
x


array([  5,  -9,  -8, -15,  16])

In [ ]:
# repeat each element of given string , times their index
s = 'python'
o = [s[i] * (i+1) for i in range(len(s))]
o

['p', 'yy', 'ttt', 'hhhh', 'ooooo', 'nnnnnn']

In [ ]:
# print missing number from 1-9 from given string l
l = [2,3,4,5,6,1,8,9]
s = [1,2,3,4,5,6,7,8,9]

for i in s:
  if i not in l:
    z = i
z

7

In [ ]:
# print even rows

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
l[1::2]

[2, 4, 6, 8]

In [ ]:
l[-1]

9

In [ ]:
# regression hackerrank problem

# Enter your code here. Read input from STDIN. Print output to STDOUT
from sklearn import linear_model
import pandas as pd
F = (input().split() )
feat = int(F[0])
row = int( F[1] )
# print(feat, row)
df = pd.DataFrame()
val = []
for i in range(row):
    value = [float(j) for j in input().split()]
    val.append(value)
df = df._append(val)

t = int(input() )
t_df = pd.DataFrame()

for i in range(t):
    value = input().split()
    val = []
    for k in range(feat):
        val.append(value)
        # print(val)
    t_df = t_df._append(val)
t_df = t_df.drop_duplicates()

modl = linear_model.LinearRegression()
modl.fit( df.iloc[:, :-1], df.iloc[:, -1:] )
ans = modl.predict(t_df)
for i in ans:
    for j in i:
        print(round(j, 2))
# print(df)

# print(t_df)

model = linear_model.LinearRegression()